logging:
  level:
    root: INFO
    lt.techin: DEBUG
    org.springframework.security: TRACE

spring:
  jackson:
    defaultPropertyInclusion: non-null
    deserialization:
      failOnUnknownProperties: false
    mapper:
      accept-case-insensitive-enums: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  security:
    user:
      name: admin
      password: password1

app:
  external:
    open-library-client:
      base: "https://openlibrary.org"
      endpoints:
        search-authors: "/search/authors.json"
        get-authors-works: "/authors/{olid}/works.json"

  secret:
    author-secret: "all your base are belong to us"
